// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDOMRe from "../node_modules/reason-react/src/ReactDOMRe.js";
import * as ReactVersionOfDomWithRef$ReasonLearningSessions from "./ReactVersionOfDomWithRef.bs.js";

ReactDOMRe.renderToElementWithId(React.createElement(ReactVersionOfDomWithRef$ReasonLearningSessions.make, { }), "root");

export {
  
}
/*  Not a pure module */
