// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as React from "react";

function CollapseToggler(Props) {
  var togglerProps = Props.togglerProps;
  var children = Props.children;
  return React.createElement("button", {
              "aria-expanded": togglerProps[/* ariaExpanded */2],
              "aria-controls": togglerProps[/* ariaControls */1],
              id: togglerProps[/* id */0],
              tabIndex: togglerProps[/* tabIndex */3],
              type: togglerProps[/* type_ */4],
              onClick: togglerProps[/* onClick */5]
            }, children);
}

var make = CollapseToggler;

export {
  make ,
  
}
/* react Not a pure module */
