// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as React from "react";

function Collapsible(Props) {
  var collapsibleProps = Props.collapsibleProps;
  var children = Props.children;
  return React.createElement("div", {
              ref: collapsibleProps[/* ref */3],
              "aria-hidden": collapsibleProps[/* ariaHidden */1],
              id: collapsibleProps[/* id */0],
              style: {
                height: collapsibleProps[/* style */4][/* height */0],
                overflow: collapsibleProps[/* style */4][/* overflow */1],
                transitionDuration: collapsibleProps[/* style */4][/* transitionDuration */3],
                transitionProperty: collapsibleProps[/* style */4][/* transitionProperty */2],
                transitionTimingFunction: collapsibleProps[/* style */4][/* transitionTimingFunction */4]
              },
              onTransitionEnd: collapsibleProps[/* onTransitionEnd */2]
            }, children);
}

var make = Collapsible;

export {
  make ,
  
}
/* react Not a pure module */
