// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as Curry from "../node_modules/bs-platform/lib/es6/curry.js";
import * as React from "react";

var counter = /* record */[/* contents */0];

function CustomId(Props) {
  var children = Props.children;
  var match = React.useState((function () {
          return 0;
        }));
  var setUid = match[1];
  React.useEffect((function () {
          Curry._1(setUid, (function (_uid) {
                  return counter[0];
                }));
          counter[0] = counter[0] + 1 | 0;
          return undefined;
        }), /* array */[]);
  return Curry._1(children, match[0]);
}

var make = CustomId;

export {
  counter ,
  make ,
  
}
/* react Not a pure module */
