// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as React from "react";
import * as CustomId$ReasonLearningSessions from "./CustomId.bs.js";

function Demo(Props) {
  return React.createElement(CustomId$ReasonLearningSessions.make, {
              children: (function (uid) {
                  return React.createElement("p", undefined, "the id is: " + String(uid));
                })
            });
}

var make = Demo;

export {
  make ,
  
}
/* react Not a pure module */
