// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as HbUidJs from "../dependencies/hb-uid.js";

var make = HbUidJs.default;

export {
  make ,
  
}
/* make Not a pure module */
