// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDOMRe from "../node_modules/reason-react/src/ReactDOMRe.js";
import * as Demo$ReasonLearningSessions from "./Demo.bs.js";

ReactDOMRe.renderToElementWithId(React.createElement(React.Fragment, undefined, React.createElement(Demo$ReasonLearningSessions.make, { }), React.createElement(Demo$ReasonLearningSessions.make, { }), React.createElement(Demo$ReasonLearningSessions.make, { }), React.createElement(Demo$ReasonLearningSessions.make, { }), React.createElement(Demo$ReasonLearningSessions.make, { })), "root");

export {
  
}
/*  Not a pure module */
