// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE


var button = document.createElement("button");

var input = document.createElement("input");

button.innerText = "Inner Text";

input.setAttribute("type", "text");

button.addEventListener("click", (function (param) {
        input.value = "Huzzah!";
        return /* () */0;
      }));

document.body.appendChild(button);

document.body.appendChild(input);

export {
  button ,
  input ,
  
}
/* button Not a pure module */
