// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as React from "react";

function $$Image(Props) {
  var imageSource = Props.imageSource;
  return React.createElement("img", {
              src: imageSource
            });
}

var make = $$Image;

export {
  make ,
  
}
/* react Not a pure module */
