// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDOMRe from "../node_modules/reason-react/src/ReactDOMRe.js";
import * as ReactReducerHook$ReasonLearningSessions from "./ReactReducerHook.bs.js";

ReactDOMRe.renderToElementWithId(React.createElement(ReactReducerHook$ReasonLearningSessions.make, { }), "root");

export {
  
}
/*  Not a pure module */
