// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as React from "react";

function ReactTest(Props) {
  var src = Props.src;
  return React.createElement("img", {
              src: src
            });
}

var make = ReactTest;

export {
  make ,
  
}
/* react Not a pure module */
