// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as Curry from '../node_modules/bs-platform/lib/es6/curry.js'
import * as React from 'react'

function ReactReducerHook(Props) {
  var match = React.useReducer(function(count, action) {
    if (action) {
      return (count - 1) | 0
    } else {
      return (count + 1) | 0
    }
  }, 0)
  var dispatch = match[1]
  return React.createElement(
    React.Fragment,
    undefined,
    React.createElement('h1', undefined, 'Reducer!'),
    React.createElement(
      'p',
      undefined,
      'Clicked ' + (String(match[0]) + ' times')
    ),
    React.createElement(
      'button',
      {
        onClick: function(_event) {
          return Curry._1(dispatch, /* Increment */ 0)
        }
      },
      'Increase'
    ),
    React.createElement(
      'button',
      {
        onClick: function(_event) {
          return Curry._1(dispatch, /* Decrement */ 1)
        }
      },
      'Decrease'
    )
  )
}

var make = ReactReducerHook

export { make }
/* react Not a pure module */
