// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as Curry from '../node_modules/bs-platform/lib/es6/curry.js'
import * as React from 'react'

function ReactStateHook(Props) {
  var match = React.useState(function() {
    return 0
  })
  var setCount = match[1]
  return React.createElement(
    React.Fragment,
    undefined,
    React.createElement(
      'p',
      undefined,
      'Clicked ' + (String(match[0]) + ' times')
    ),
    React.createElement(
      'button',
      {
        onClick: function(_event) {
          return Curry._1(setCount, function(count) {
            return (count + 1) | 0
          })
        }
      },
      'Increase'
    ),
    React.createElement(
      'button',
      {
        onClick: function(_event) {
          return Curry._1(setCount, function(count) {
            return (count - 1) | 0
          })
        }
      },
      'Decrease'
    )
  )
}

var make = ReactStateHook

export { make }
/* react Not a pure module */
