// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as Curry from "../node_modules/bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Caml_option from "../node_modules/bs-platform/lib/es6/caml_option.js";

function getInitialHeight(isOpenProp, defaultOpen, maxHeight, collapsedHeight) {
  var exit = 0;
  var exit$1 = 0;
  if (isOpenProp !== undefined && isOpenProp) {
    exit = 1;
  } else {
    exit$1 = 2;
  }
  if (exit$1 === 2) {
    if (defaultOpen !== undefined) {
      if (defaultOpen) {
        exit = 1;
      } else {
        return String(collapsedHeight) + "px";
      }
    } else {
      return String(collapsedHeight) + "px";
    }
  }
  if (exit === 1) {
    if (maxHeight !== undefined) {
      return String(maxHeight) + "px";
    } else {
      return "auto";
    }
  }
  
}

function getIsOpen(isOpenProp, isOpenState) {
  if (isOpenProp !== undefined) {
    return Caml_option.valFromOption(isOpenProp);
  } else {
    return isOpenState;
  }
}

function Collapse(Props) {
  var isOpenProp = Props.isOpen;
  var defaultOpen = Props.defaultOpen;
  var match = Props.collapsedHeight;
  var collapsedHeight = match !== undefined ? match : 0;
  Props.duration;
  Props.timingFunction;
  Props.closeDuration;
  Props.closeTimingFunction;
  Props.openDuration;
  Props.openTimingFunction;
  var maxHeight = Props.maxHeight;
  var children = Props.children;
  getInitialHeight(isOpenProp, defaultOpen, maxHeight, collapsedHeight);
  var collapsibleRef = React.useRef(null);
  var match$1 = React.useState((function () {
          var exit = 0;
          if (isOpenProp !== undefined && isOpenProp) {
            return true;
          } else {
            exit = 1;
          }
          if (exit === 1) {
            if (defaultOpen !== undefined && defaultOpen) {
              return true;
            } else {
              return false;
            }
          }
          
        }));
  var isOpenState = match$1[0];
  React.useEffect((function () {
          var isOpen = getIsOpen(isOpenProp, isOpenState);
          var match = collapsibleRef.current;
          if (!(match == null)) {
            if (isOpen && match.clientHeight !== 0) {
              var height = maxHeight !== undefined ? String(maxHeight) + "px" : "auto";
              match.style.height = height;
            }
            if (!isOpen && collapsedHeight === 0) {
              match.style.display = "none";
            }
            
          }
          return undefined;
        }), /* array */[]);
  return Curry._1(children, 10);
}

var defaultDuration = 300;

var defaultTimingFunction = "cubic-bezier(0.09, 1.03, 0.57, 0.97)";

var make = Collapse;

export {
  defaultDuration ,
  defaultTimingFunction ,
  getInitialHeight ,
  getIsOpen ,
  make ,
  
}
/* react Not a pure module */
