// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDOMRe from "../node_modules/reason-react/src/ReactDOMRe.js";
import * as Collapse$ReasonLearningSessions from "./Collapse.bs.js";

ReactDOMRe.renderToElementWithId(React.createElement(Collapse$ReasonLearningSessions.make, {
          children: (function (number) {
              return React.createElement("div", undefined, String(number));
            })
        }), "root");

export {
  
}
/*  Not a pure module */
